Traceback (most recent call last):
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print('It's time')

------------------


[0;36m  Cell [0;32mIn[9], line 1[0;36m[0m
[0;31m    print('It's time')[0m
[0m                    ^[0m
[0;31mSyntaxError[0m[0;31m:[0m unterminated string literal (detected at line 1)


